version: '3'
services:
    gothmog-web:
        build: .
        container_name: gothmog-web
        entrypoint:
            - node
            - /app/web/app.js
        ports:
            - "${WEB_PORT:-80}:8080"
